### ISSUE TITLE
Deleting Maps with lots of content causes problems

### ISSUE THREAD

**Issue by mcomp** [CompendiumNG/CompendiumNG#257] opened 2015-01-08 10:13 UTC
Deleting Maps with lots of content leaves compendium not responding for a long time (up to several minutes). We experienced this problem when trying to delete a map containing 27 different nodes, of which six are maps. These again contained around 50 nodes and maps (with minor contents).
We noticed that upon deleting very many MySQL-packets are sent.
(tested with Compendium Version 2.0 beta 1 run on Linux Mint 13 Xfce)

**Comment by mike223** [comment] 2015-07-16 10:12
epasseto    thinks the problem is connected to a high total number of maps:
"For my project (11.500 Map nodes), it takes more than 11 minutes to delete only ONE Map node from your current view or list"
http://www.compendiumng.org/questions/improve-delete-map-node-routine/

The database of mcomp contains about 3k maps.

[showstopper]

**Comment by mike223** [comment] 2015-07-16 22:25
Bug is still there with 2.1.5 and even worse:
Even after one hour a map was not deleted. CPU 80% java, 20% mysqld. 
Using almost the same database with 2.0 Beta1 took "only" 2.5 minutes to delete the map. 

Similiar setup to the one of mcomp.
No difference between OpenJDK 7 und Oracle Java 7.

**Comment by maiklos** [comment] 2016-01-10 12:45
could you please someone excercise this issue and send log file ?
I don't have any huge maps for testing this issue

**Comment by maiklos** [comment] 2018-02-13 11:22
closing. It can be reopened when we have:
clear testcase that demonstrate the problem including the available map

**Closed as completed** 2018-02-13 11:22 UTC
Labels: Type: Bug, Level: General, try-to-replicate
