### ISSUE TITLE
Installer on Windows 7 problems

### ISSUE THREAD

**Issue by kenglover** [CompendiumNG/CompendiumNG#212] opened 2013-12-22 21:25 UTC
Hello,

Thanks for all the work on CompendiumNG.

Using the installer (jar) from build 42 (Dec 17) I observed the following:
1. The installation path has unresolved symbols in it - "C:\Program Files/${project.name}/v${project.version}"
2. When I change the installation path to "C:\Program Files\CompendiumNG" I get an error "PathInputPanel.noWhiteSpaces"
3. Installing to a different location, the program will not start up using the bat file unless I run as an administrator.

OS: Windows 7
java version "1.7.0_45"
Java(TM) SE Runtime Environment (build 1.7.0_45-b18)
Java HotSpot(TM) 64-Bit Server VM (build 24.45-b08, mixed mode)

**Comment by maiklos** [comment] 2014-01-20 01:05
IMO 212/2 and 212/3 might be also fixed since it seems to be caused by 212/1.
We will need to retest it.

**Comment by kenglover** [comment] 2014-01-20 04:48
Problems 1 and 3 are resolved with build 50.
I had to remove the previously created folders in my user directory before #3 was resolved.

**Comment by maiklos** [comment] 2014-01-21 21:29
212/2 is fixed in build 51

**Closed as completed** 2014-01-21 21:35 UTC
Labels: Type: Bug, Level: General

**Comment by kenglover** [comment] 2014-01-22 00:52
Tested successfully, thanks Maiklos.

Ken
