### ISSUE TITLE
Zooming vs map panning with Mac multi-touch mouse pad

### ISSUE THREAD

**Issue by alselvin** [CompendiumNG/CompendiumNG#207] opened 2013-11-01 17:57 UTC
It's great that moving two fingers together on the multi-touch mouse pad zooms in and out, but I did not see a way to do the traditional Compendium map panning action of "right-click" (Option key on Mac) and drag. The only way to pan the map seems to be to use the arrow keys or thumbs, is that correct? 

If so, I suggest that Option-two fingers would pan the map. At present that action doesn't seem to do anything.

**Comment by SebastianBoell** [comment] 2014-09-23 08:51
I have tested this on Mac for the current cutting edge version. The behavior is as intended. If using two fingers users can pan up and down or left and right. If holding the ontrol key and using two finders CNG zooms in and out.

I will close this issue now. We can re-open if we have additional reports replicating the issue.

**Closed as completed by SebastianBoell** 2014-09-23 08:51 UTC
Labels: Type: Feature, platform specific, Level: General, try-to-replicate
