### ISSUE TITLE
Help search index lists results twice

### ISSUE THREAD

**Issue by SebastianBoell** [CompendiumNG/CompendiumNG#60] opened 2012-12-30 05:13 UTC
http://compendium.open.ac.uk/bugzilla/show_bug.cgi?id=882

Michelle Bachler 2010-05-28 16:41:24 BST

This was reported by a user.

I will look at building the help indexes again and I'll put a patch here for
people to get if they want to fix their help before Beta 2 is out.

Michelle

[reply] [-] Comment 1 Michelle Bachler 2010-05-28 18:10:02 BST

Created an attachment (id=424) [details]
New Help indexes

Replace you <compendium dir>/System/resources/Help/JavaHelpSearch folder with
the one in this zip

**Comment by SebastianBoell** [comment] 2012-12-30 05:14
Cannot confirm this for M1. Search only lists each item once. Michal if you also cannot find this issue to apply in M1 I suggest closing.

**Comment by maiklos** [comment] 2013-02-26 22:59
couldn't reproduces this. closing.

**Closed as completed by maiklos** 2013-02-26 22:59 UTC
Labels: Type: Bug, Level: General
