### ISSUE TITLE
unable to create admin db (derby) on Mac 

### ISSUE THREAD

**Issue by maiklos** [CompendiumNG/CompendiumNG#219] opened 2014-04-22 22:04 UTC
Two users reported issue with initial creation of admin database on Mac
(http://www.compendiumng.org/topic/launch-issue-cant-create-database-cngadmindb/)

**Comment by SebastianBoell** [comment] 2014-04-24 06:19
The installer worked very smooth on Mac. 

I can confirm that installation is correctly into the applications floder. Though trying to start CNG is painful. Users have to go into the folder select CompendiumNG.sh. Then right click select open with and then select 'Terminal' from utilities which is initially grayed out. So users have to select 'enable all applications'. This starts CNG, but only a little for producing the following output:

```
Exception in thread "main" java.lang.UnsupportedClassVersionError: com/compendium/ProjectCompendium : Unsupported major.minor version 51.0
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:621)
    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
    at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
    at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
```

Note: 
I installed Java 7 version 55 prior to installation.
This may be a different bug from the one reported for #219 but without it being resolved I cannot do further testing :(

**Comment by djbclark** [comment] 2014-04-24 09:21
I also have both of these problems, Mavricks, latest Java 7, when I open the .jar I get the former problem, when I run the shell script the later.

**Comment by djbclark** [comment] 2014-04-24 09:47
Well that's messed up... it looks like the Mac OS X JRE install doesn't put the JRE where apps expect it. So the UnsupportedClassVersionError is complaining about Apple's Java 6 (that comes with Mavricks). This works to start CompendiumNG fine after Java 7 JRE is installed:

cd /Applications/CompendiumNG/

/Library/Internet\ Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/bin/java -Dlogback.configurationFile="/Applications/CompendiumNG/logback.xml" -Dcompendiumng.config.dir=${HOME}/compendiumng_config -Ddir.data=${HOME}/compendiumng_data -Xmx512m -jar CompendiumNG.jar

I also manually created the two referenced home directory folders while figuring this out, but that might just happen automatically...

**Comment by djbclark** [comment] 2014-04-24 09:51
(Actually it starts up as like a 50 by 200 pixel fragment of a title bar, but you can just expand that to get the normal large window.)

**Comment by SebastianBoell** [comment] 2014-05-01 05:28
I can confirm that startup of CNG works fine with the changed path as above. I will now try to figure out how to create a propper APP file to make this thing work as intended.

**Comment by SebastianBoell** [comment] 2014-05-02 03:13
I cannot replicate this issue. The script by djbclak works fine and starts CNG. I will close this issue. If we can replicate the problem or get further reports we can re-open. I will work now on issu #160.

**Closed as completed by SebastianBoell** 2014-05-02 03:13 UTC

**Comment by atknapp** [comment] 2015-04-23 11:11
Still having problems with CompendiumNG 2.1.4 on OS X (10.10.3) and Java 8.45:

![screen shot 2015-04-23 at 11 58 56](https://cloud.githubusercontent.com/assets/12083199/7295763/3699a9be-e9b1-11e4-8509-569d7b6d88bb.png)

I then open Terminal and type in:

cd /Applications/CompendiumNG/

and

/Library/Internet\ Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/bin/java -Dlogback.configurationFile="/Applications/CompendiumNG/logback.xml" -Dcompendiumng.config.dir=${HOME}/compendiumng_config -Ddir.data=${HOME}/compendiumng_data -Xmx512m -jar CompendiumNG.jar

![screen shot 2015-04-23 at 11 59 28](https://cloud.githubusercontent.com/assets/12083199/7295810/89a972f6-e9b1-11e4-8ea2-eb2c8fc323da.png)

and CompendiumNG starts up successfully and is functional (once I expand it) from the title bar it seems to default to:

![screen shot 2015-04-23 at 11 59 48](https://cloud.githubusercontent.com/assets/12083199/7295825/a59a12d6-e9b1-11e4-9743-8ceb4c96a1cc.png)

However, as soon as I quit the Terminal app, it closes CompendiumNG:

![screen shot 2015-04-23 at 12 00 51](https://cloud.githubusercontent.com/assets/12083199/7295834/b5fb1c9c-e9b1-11e4-96a7-d38555f9c336.png)

and I've got to go through the entire process again to open it back up.  Every time.

Is there some way to make the terminal commands 'stick'?  Or am I doing something wrong?

**Comment by SebastianBoell** [comment] 2015-04-23 13:28
I used a tool called Platypus to create a proper Mac starter for CNG (http://www.sveinbjorn.org/platypus). The tool is very simple and basically only needs the startup line. The tool then creates a proper application folder structure. The plan is to use this tool to supply the Mac version of CNG. Unfortunately there seems to be an issue with the resulting application only working on the machine on which it was created. When I upload the script to the CNG repository and include it in the installer the thing falls apart. This is very annoying :( 
Maybe you can try using Platypus and see if it works for you at least locally?
The above issue is tracked under the open issue #160

**Comment by Yerual** [comment] 2015-08-07 09:14
Hello, I am trying again after more than a year to install CompendiumNG on my Mac (Yosemite 10.10.4, Java 8 just downloaded and installed). I can see no straightforward way to launch the program after installing it (i.e., I don't what icon to double-click). Also in this thread I see no one simple way to get this to work. Can anyone help me? Has this issue been resolved for others?

I really hope to start working with Compendium again, I've had good experiences in the past...

**Comment by SebastianBoell** [comment] 2015-08-18 11:58
Hi Yerual,

Unfortunately this issue has not been resolved. It seems that over the
last few years Apple has increased the security requirements for
generating scripts for starting programs that can be ported across
different machines easily.

I did some research into this and it will require us to get an developer
ID from Apple in order to release a proper .app file that will work as
starter.

For now you can try the following two commands:
cd /Applications/CompendiumNG
/Library/Internet\ Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/bin/java -Dlogback.configurationFile="/Applications/CompendiumNG/logback.xml" -Dcompendiumng.config.dir=${HOME}/compendiumng_config -Ddir.data=${HOME}/compendiumng_data -Xmx512m -jar CompendiumNG.jar

If these commands work for you you can creade a startup script for them.
You may even create an .app starter using platypus. This will make CNG
behave like a regular Mac application.

Sorry for the inconvenience at this point. I will look more thoroughly
into this apple developer ID to rectify this issue for good in the
future.

Cheers

**Comment by Yerual** [comment] 2015-08-18 12:51
Thanks Sebastian,

I might try the commands you suggest, when I find the courage ;D

Best,
Leon

**Comment by nathan-artist** [comment] 2015-10-06 19:25
I just installed CompendiumNG 2.1.4 on a Mac running OS X Mavericks 10.9.5 (and Java 1.8.0.60), and I encountered most of the same problems mentioned above, as I expect all Mac users do. In my view, the "user experience" of trying to run CompendiumNG 2.1.4 on OS X is quite bad.

For years, I used Compendium 2.0 Beta 1 on a Mac running OS X Tiger 10.4.11 without any problems except for the fact that the Compendium window was always on top of all other applications unless the window was minimized. The "user experience" of running Compendium 2.0 Beta 1 on OS X Tiger was rock-solid in comparison to CompendiumNG 2.1.4 on OS X Mavericks. I wish I could help improve CompendiumNG 2.1.4 but I don't have the requisite programming skills.

As I pointed out in my comment on <a href="https://github.com/CompendiumNG/CompendiumNG/issues/160">issue #160: Mac users report there should be .app file for starting CNG</a>, you don't need Platypus to create a proper Mac app for CompendiumNG 2.1.4; you can also use <a href="http://en.wikipedia.org/wiki/AppleScript">AppleScript</a>, which comes with OS X (see my comment on <a href="https://github.com/CompendiumNG/CompendiumNG/issues/160">issue #160</a> for details).

Once I managed to overcome all of the obstacles mentioned above, I immediately encountered more bugs in CompendiumNG 2.1.4, which I will report elsewhere.
