### ISSUE TITLE
Software seems to seek for something after you try to import an xml file which is corrupted

### ISSUE THREAD

**Issue by SebastianBoell** [CompendiumNG/CompendiumNG#89] opened 2013-01-01 12:07 UTC
http://compendium.open.ac.uk/bugzilla/show_bug.cgi?id=972

-- no further details given --

**Comment by SebastianBoell** [comment] 2013-01-01 12:07
We would need a corrupted xml file to test for this bug.

**Comment by maiklos** [comment] 2013-01-01 13:21
well, I think when the xml export file is corrupted then it is corrupted. We will not support import of corrupted exports.

I would suggest to make checksum/validation check prior to import however we should also keep compatible behavior for importing old project exports - that's why I don't want to modify importer/exporter behavior what would break the compatibility (adding checksum would break certainly break it)

not a bug from my point of view.

**Comment by SebastianBoell** [comment] 2013-01-02 02:09
I agree we should not waste any time on working on corrupted files. However, if I understood the problem correctly the issue is that Compendium should simply give an error message than be hanging in a loading stage.

Having a checksum in xml export may be a good addition. I guess this should then be a new issue. Regarding the problem that you describe. Could Compendium have the checksum in a node? Then old version would only import an additional node (hence backwards compability). New versions that support the checksum would see if the node is there and then check the document against it. If the node is not there then the domument would simply be imported without doing a check first (hence forward compability).

**Comment by maiklos** [comment] 2013-01-02 04:37
I can review the import code if there are some risks of cycling (what original ticket suggests) but implementing optional checksum doesn't seem reasonable.

**Comment by SebastianBoell** [comment] 2013-01-02 06:50
I agree you can have a look and then maybe close this issue. We can reopen it should there be reports in the future of hanging of CompendiumNG on import.

**Comment by maiklos** [comment] 2013-02-26 23:19
I tried to import some corrupted files with following result.
a) file cut in the middle: will not pass validation and CNG will display error message (OK)
b) randomly modified some values -> CNG just imported the file as it was valid

from the code I don't see any potential problems so I am closing this issue.
we can reopen when we have some reproducible case with corrupted export sample that causes the problem.

**Closed as completed by maiklos** 2013-02-26 23:19 UTC
Labels: Type: Other, Level: Minor
