### ISSUE TITLE
Compendium holds the focus and won't let other windows in front

### ISSUE THREAD

**Issue by SebastianBoell** [CompendiumNG/CompendiumNG#49] opened 2012-12-30 04:16 UTC
http://compendium.open.ac.uk/bugzilla/show_bug.cgi?id=853

Michelle Bachler 2010-04-30 20:02:45 BST

This can happen especially after you have just installed Compendium.

After that it is usually occasional and random.
We have found no pattern.
There is no code designed to do this behaviour in Compendium.
We are investigating.
All observations are welcome.

If you minimise Compendium, or restart it, you should be ok.

[reply] [-] Comment 1 Michelle Bachler 2010-04-30 20:05:09 BST

Apparently minimising does not always help.
Then you have to restart Compendium

[reply] [-] Comment 2 Michelle Bachler 2010-06-07 10:54:17 BST

**\* Issue 887 has been marked as a duplicate of this issue. ***

[reply] [-] Comment 3 Michelle Bachler 2010-07-05 12:28:00 BST

**\* Issue 901 has been marked as a duplicate of this issue. ***

[reply] [-] Comment 4 Michelle Bachler 2010-10-15 15:26:24 BST

**\* Issue 936 has been marked as a duplicate of this issue. ***

[reply] [-] Comment 5 Michelle Bachler 2010-10-18 09:42:57 BST

**\* Issue 937 has been marked as a duplicate of this issue. ***

[reply] [-] Comment 6 Michelle Bachler 2010-12-16 09:36:39 GMT

**\* Issue 949 has been marked as a duplicate of this issue. ***

[reply] [-] Comment 7 Michelle Bachler 2011-01-19 09:52:44 GMT

**\* Issue 973 has been marked as a duplicate of this issue. ***

[reply] [-] Comment 8 Michelle Bachler 2011-10-27 12:46:46 BST

**\* Issue 1020 has been marked as a duplicate of this issue. ***

**Comment by SebastianBoell** [comment] 2012-12-30 04:20
Given so many reports of this problem I assigned it a critical status. 

I know this issue from my own working with Compendium, it is bound to happen but so far nobody has found a means to consistantly replicate it. 

For me it happens regularely when opening PDF's linked through compendium. As they are opened in the background (behind Compendium) and grab the focus it can even give the false impression the Compendium is frozen. Closing the PDF viewer at least let's one work with Compendium again.

**Comment by maiklos** [comment] 2012-12-30 04:29
I am not surprised by this behavior. Event handlers are often starting long running operations (like opening external file) in the same thread. Will try to fix this in M1.

**Comment by maiklos** [comment] 2013-01-05 01:16
I added action handling logging with detection of overdue (>500ms) processing in cd02a and merged into M1
If event processing takes longer that 500ms it will be logged with error severity.

now, it would be nice to catch the situation on M1with debug log on

**Comment by SebastianBoell** [comment] 2013-01-06 04:39
Hopefully this will help us to get to the bottom of this nasty bug. I will keep my eyes open for when it appears. Unfortunately it is something quite irregular.

**Comment by SebastianBoell** [comment] 2013-01-07 12:51
I just had this behaviour, but cannot find any file under System/resource/Logs. Will run Compendium from the Console next time. As often as I open external linked files as part of the feature request this is bound to happen again soon :)

**Comment by maiklos** [comment] 2013-01-07 20:32
logs for CompendiumNG are in log directory however this will not be necessary. The behavior is different than I originally thought. I think I have found the cause of the problem. I will commit a the fix for testing soon.

**Comment by maiklos** [comment] 2013-01-08 00:33
how to reproduce the problem:
1) open compendium
2) on any map create a node (any type) (Node A)
3) select Node A and you will see 4 triangles top/right/down/left
4) left click on one of them and pop-up menu with node type will appear
5) select one of them
6) now if you try to choose another application and maximize it will not be possible. Compendium will stay on top of windows stack until you explicitly minimize it. Also shutdown/startup of compendium will remedy this behavior ... until you trigger the problem again.

it is possible that this problem can be triggered also in other way.

Problem is fixed in commit 51c8f  which is merged into the M1 branch now.

**Closed as completed** 2013-01-09 00:01 UTC
Labels: Type: Bug, Level: Critical

**Comment by usabilidoido** [comment] 2013-02-25 15:17
For those who are still using Compendium 2.0, I found a workaround for this bug. Download this Autokey script that sets a window to stay allways on top https://www.box.com/shared/4ej5cqoekj Execute the file, switch to the Compendium window and press CTRL+Space twice (one to activate, second to deactivate). From now on it's fixed.

**Comment by Australian-Infomaniac** [comment] 2013-06-22 07:48
I really think just having a work around you have to do every time is far from acceptable.
I can certainly duplicate this - it happens EVERY TIME I use compendium.
It is rendering the app almost useless, wasting everyone's work.
I use C with lots of other apps, collecting information in, and sending it out. So it really restricts the use.
It's also very irritating and a real problem when one is working to a deadline.

Please someone fix this - it's the only major bug that keeps bothering me lol !

**Comment by Australian-Infomaniac** [comment] 2013-06-22 07:54
actually, has this been merged into the program, ie. 2 beta ne? I do have 2 beta, but i got it a few months ago

**Comment by Australian-Infomaniac** [comment] 2013-06-22 08:04
Thanks usabilidoido for the fix - it seems to work!

---

But really, it's far from ideal. Having to do that rigmerole every time just increases the barrier to use. Furthermore, it may be symptomatic of other problems. 

BTW: is the standard C still being developed? 
I read about three other versions (LD, DS, CN)  but it was rather confusing...be good to have a few screenshots showing the difference between them, or one of those comparison tables.

---

Anyway, I've had a long love affair (sometimes a stormy one !) with this awesome app so its a shame that the old "should i bother - can i use something else?" thought comes up when i'd like to use C but I need a smooth workflow because i'm on a deadline.

**Comment by Australian-Infomaniac** [comment] 2013-06-22 08:05
Actually, i'd be really grateful if someone could just point me to which of the three new versions i should use if im already happy with the old standard one.

**Comment by maiklos** [comment] 2013-06-22 21:14
this issue tracker is dedicated to CompendiumNG which is trying to be continuation of the original Compendium.
If you still have the problem then it means that you are using Compendium (or any version that is derived from it and inherits the problem) but not current version of CompendiumNG for which this problem has been already localized, described and fixed 6 months ago (see my closing post for details). If you read how to reproduce it it must be clear to you how to avoid it: Simply don't use triangles to create new nodes. usabilidoido's workaround might work as well but I have to agree with you that it is far from ideal. If you want to stay with the original Compendium you may ask in compendium yahoo group for fix (you may refer this issue because it shows exactly how to fix it - it is pretty trivial fix after all). Alternatively you can fix it yourself and recompile Compendium.

Regarding Compendium variants (mentioned here: http://compendium.open.ac.uk/institute/download/download.htm)
here we work on CompendiumNG which is derived from the original Compendium. That means that
 we fix bugs in CompendiumNG code (not in Compendium code)  including inherited bugs from the original Compendium. Also fixed bugs in CompendiumNG will not be auto-magically fixed in Compendium.

I suggest you to use (or at least to try) CompendiumNG.
